version: '3.8'

services:
  # Веб-приложение
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - DJANGO_SETTINGS_MODULE=servisdesk.settings_production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALLOWED_HOSTS=192.168.0.149,localhost,127.0.0.1
      - DB_HOST=db
      - DB_NAME=servisdesk
      - DB_USER=servisdesk
      - DB_PASSWORD=${DB_PASSWORD:-servisdesk123}
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    networks:
      - servisdesk-network

  # База данных PostgreSQL (опционально)
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=servisdesk
      - POSTGRES_USER=servisdesk
      - POSTGRES_PASSWORD=${DB_PASSWORD:-servisdesk123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - servisdesk-network

  # Redis для кеширования (опционально)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - servisdesk-network

  # Nginx (если нужен отдельный веб-сервер)
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/var/www/staticfiles
      - ./media:/var/www/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - servisdesk-network

volumes:
  postgres_data:
  redis_data:

networks:
  servisdesk-network:
    driver: bridge
